Update models_checklist.md
itlab-vision/openvino-dl-benchmark pull request #181
Opened 2020-09-18 01:43 UTC by Makarov-AA

Отметил модели, занесенные в валидационную таблицу. Внес необработанные модели в модели для следующего этапа расширения. Также внес туда новые модели из 2020.4 версии, а также публичные модели из [этого](https://docs.openvinotoolkit.org/latest/omz_models_public_index.html) списка

2020-09-25 16:15 UTC, Makarov-AA commented
@KchnKchn посмотрите, пожалуйста, оформление cheklist

2020-09-25 16:20 UTC, KchnKchn requested changes
@Makarov-AA. исправляйте замечание. Остальное все хорошо.

2020-09-25 16:20 UTC, KchnKchn commented on results/models_checklist.md
> +1. resnet50-binary-0001
Это тот же самый резнет50, только с квантизированными весами. Его отсюда нужно убрать

2020-09-27 10:13 UTC, KchnKchn approved these changes
@AlibekovMurad5202, когда файл зальется в мастер. Обновите его в соответствии с теми моделями, которые вы добавили.

@Makarov-AA, можно мержить

2020-09-27 16:17 UTC, merged